In [1]:
import pandas as pd
import numpy as np

data = {
    "order_id": [1,2,3,4,5,6,7,8,9,10],
    "customer": ["A","B","A","C","B","A","C","B","A","C"],
    "product": ["Laptop","Mobile","Tablet","Laptop","Tablet","Mobile","Mobile","Laptop","Tablet","Mobile"],
    "price": [50000,20000,15000,52000,14000,21000,19000,51000,np.nan,20000],
    "quantity": [1,2,1,1,3,1,2,1,2,1],
    "city": ["Bangalore","Delhi","Bangalore","Mumbai","Delhi","Bangalore","Mumbai","Delhi","Bangalore","Mumbai"]
}

df = pd.DataFrame(data)

In [7]:
df

   order_id customer product    price  quantity       city
0         1        A  Laptop  50000.0         1  Bangalore
1         2        B  Mobile  20000.0         2      Delhi
2         3        A  Tablet  15000.0         1  Bangalore
3         4        C  Laptop  52000.0         1     Mumbai
4         5        B  Tablet  14000.0         3      Delhi
5         6        A  Mobile  21000.0         1  Bangalore
6         7        C  Mobile  19000.0         2     Mumbai
7         8        B  Laptop  51000.0         1      Delhi
8         9        A  Tablet      NaN         2  Bangalore
9        10        C  Mobile  20000.0         1     Mumbai

In [10]:
# How many missing values are present in each column

print(df.isnull().sum())

order_id    0
customer    0
product     0
price       1
quantity    0
city        0
dtype: int64

In [29]:
# Replace missing values in price column with:
# mean of the price column

mean_value = df["price"].mean()
df["price"].fillna(mean_value, inplace=True)
print(df)

   order_id customer product         price  quantity       city
0         1        A  Laptop  50000.000000         1  Bangalore
1         2        B  Mobile  20000.000000         2      Delhi
2         3        A  Tablet  15000.000000         1  Bangalore
3         4        C  Laptop  52000.000000         1     Mumbai
4         5        B  Tablet  14000.000000         3      Delhi
5         6        A  Mobile  21000.000000         1  Bangalore
6         7        C  Mobile  19000.000000         2     Mumbai
7         8        B  Laptop  51000.000000         1      Delhi
8         9        A  Tablet  29111.111111         2  Bangalore
9        10        C  Mobile  20000.000000         1     Mumbai

In [53]:
# For each customer:

# total revenue
# average quantity

df["revenue"] = df["price"] * df["quantity"]

result = df.groupby("customer").agg(
    total_revenue = ("revenue", "sum"),
    average_quantity = ("quantity", "mean")
)

result

          total_revenue  average_quantity
customer
A         144222.222222          1.250000
B         133000.000000          2.000000
C         110000.000000          1.333333

In [62]:
# For each customer and product combination:

# total revenue

result = df.groupby(["customer", "product"]).agg(
    total_revenue = ("revenue", "sum")
)

result

                  total_revenue
customer product
A        Laptop    50000.000000
         Mobile    21000.000000
         Tablet    73222.222222
B        Laptop    51000.000000
         Mobile    40000.000000
         Tablet    42000.000000
C        Laptop    52000.000000
         Mobile    58000.000000

In [84]:
# Customers whose total revenue is greater than 60,000
# AND show their average quantity also

result = df.groupby("customer").agg(
    total_revenue = ("revenue", "sum"),
    average_quantity = ("quantity", "mean")
)

result.query("total_revenue > 60000")

          total_revenue  average_quantity
customer
A         144222.222222          1.250000
B         133000.000000          2.000000
C         110000.000000          1.333333

In [97]:
# For each city
# The customer who generated highest revenue

revenue_per_customer = df.groupby(["city", "customer"])["revenue"].sum().reset_index()

result = revenue_per_customer.loc[
    revenue_per_customer.groupby("city")["revenue"].idxmax()
]

result

        city customer        revenue
0  Bangalore        A  144222.222222
1      Delhi        B  133000.000000
2     Mumbai        C  110000.000000