In [1]:
import pandas as pd

data = {
    "order_id": [101, 102, 103, 104, 105, 106, 107, 108],
    "customer": ["A", "B", "A", "C", "B", "A", "C", "B"],
    "product": ["Laptop", "Mobile", "Tablet", "Laptop", "Tablet", "Mobile", "Mobile", "Laptop"],
    "price": [50000, 20000, 15000, 52000, 14000, 21000, 19000, 51000],
    "quantity": [1, 2, 1, 1, 3, 1, 2, 1],
    "date": pd.to_datetime([
        "2024-01-01", "2024-01-02", "2024-01-03", "2024-01-04",
        "2024-01-05", "2024-01-06", "2024-01-07", "2024-01-08"
    ])
}

df = pd.DataFrame(data)

In [2]:
df

   order_id customer product  price  quantity       date
0       101        A  Laptop  50000         1 2024-01-01
1       102        B  Mobile  20000         2 2024-01-02
2       103        A  Tablet  15000         1 2024-01-03
3       104        C  Laptop  52000         1 2024-01-04
4       105        B  Tablet  14000         3 2024-01-05
5       106        A  Mobile  21000         1 2024-01-06
6       107        C  Mobile  19000         2 2024-01-07
7       108        B  Laptop  51000         1 2024-01-08

In [8]:
print(df.head(5))

   order_id customer product  price  quantity       date
0       101        A  Laptop  50000         1 2024-01-01
1       102        B  Mobile  20000         2 2024-01-02
2       103        A  Tablet  15000         1 2024-01-03
3       104        C  Laptop  52000         1 2024-01-04
4       105        B  Tablet  14000         3 2024-01-05

In [7]:
print(df.tail(3))

   order_id customer product  price  quantity       date
5       106        A  Mobile  21000         1 2024-01-06
6       107        C  Mobile  19000         2 2024-01-07
7       108        B  Laptop  51000         1 2024-01-08

In [12]:
# Number of rows and columns in the dataset
# Column names

print(df.shape)
print(df.columns)

(8, 6)
Index(['order_id', 'customer', 'product', 'price', 'quantity', 'date'], dtype='object')

In [21]:
 # Q3 : # Only customer and product columns
# Show first 5 rows of that result

print(df[["customer", "product"]].head(5))

  customer product
0        A  Laptop
1        B  Mobile
2        A  Tablet
3        C  Laptop
4        B  Tablet

In [32]:
 # Q4 : Show all rows where:
# price > 20000

print(df[df["price"] > 20000])

   order_id customer product  price  quantity       date
0       101        A  Laptop  50000         1 2024-01-01
3       104        C  Laptop  52000         1 2024-01-04
5       106        A  Mobile  21000         1 2024-01-06
7       108        B  Laptop  51000         1 2024-01-08

In [62]:
# Q4 : Show rows where:
# product = "Laptop"
# AND price > 50000

df[(df["product"] == "Laptop") & (df["price"] > 50000)]

   order_id customer product  price  quantity       date
3       104        C  Laptop  52000         1 2024-01-04
7       108        B  Laptop  51000         1 2024-01-08

In [ ]:
#  Q5 : Show rows where:
# customer is "A"
# OR quantity >= 2

In [65]:
df[(df["customer"] == "A") | (df["quantity"] >= 2 )]

   order_id customer product  price  quantity       date
0       101        A  Laptop  50000         1 2024-01-01
1       102        B  Mobile  20000         2 2024-01-02
2       103        A  Tablet  15000         1 2024-01-03
4       105        B  Tablet  14000         3 2024-01-05
5       106        A  Mobile  21000         1 2024-01-06
6       107        C  Mobile  19000         2 2024-01-07